version: '3.8'

services:
  backend:
    build: .
    container_name: social-media-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/social-media
      - JWT_SECRET=your_jwt_secret_key
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
    networks:
      - social-network

  mongo:
    image: mongo:5.0
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - social-network

volumes:
  mongo-data:

networks:
  social-network:
    driver: bridge
